name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and test
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: integration-bot-test
          platforms: linux/amd64

  deploy:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to SIA Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.REGISTRY_URL }}/integration/bot:latest
            ${{ secrets.REGISTRY_URL }}/integration/bot:${{ github.sha }}
            ${{ secrets.REGISTRY_URL }}/integration/bot:${{ github.run_number }}
          platforms: linux/amd64
